services:
  - type: web
    name: kosmi-rave-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: FRONTEND_URL
        sync: false
